---
- name: Ensure compose base directory exists
  ansible.builtin.file:
    path: "{{ docker_compose_base_dir }}"
    state: directory
    mode: '0755'
  become: true

- name: Aggregate compose projects for host
  ansible.builtin.set_fact:
    docker_compose_projects_effective: "{{ (docker_compose_projects | default([])) + (docker_compose_projects_host | default([])) }}"

- name: Ensure compose project directories exist
  ansible.builtin.file:
    path: "{{ docker_compose_base_dir }}/{{ item.name }}"
    state: directory
    mode: '0755'
  loop: "{{ docker_compose_projects_effective }}"
  when: item.state | default('present') == 'present'
  become: true

- name: Render docker-compose.yml for each project
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_base_dir }}/{{ item.name }}/docker-compose.yml"
    mode: '0644'
  loop: "{{ docker_compose_projects_effective }}"
  when: item.state | default('present') == 'present'
  become: true

- name: Bring compose projects online
  ansible.builtin.command:
    cmd: "docker compose up {{ docker_compose_up_flags }}"
    chdir: "{{ docker_compose_base_dir }}/{{ item.name }}"
  register: docker_compose_up
  changed_when: >-
    ('Creating' in docker_compose_up.stdout) or
    ('Recreating' in docker_compose_up.stdout) or
    ('Pulling' in docker_compose_up.stdout) or
    ('Creating' in docker_compose_up.stderr) or
    ('Recreating' in docker_compose_up.stderr)
  loop: "{{ docker_compose_projects_effective }}"
  when:
    - docker_manage_compose | bool
    - item.state | default('present') == 'present'
  become: true

- name: Tear down disabled compose projects
  ansible.builtin.command:
    cmd: "docker compose down --remove-orphans"
    chdir: "{{ docker_compose_base_dir }}/{{ item.name }}"
  register: docker_compose_down
  changed_when: >-
    ('Stopping' in docker_compose_down.stdout) or
    ('Removing' in docker_compose_down.stdout) or
    ('Stopping' in docker_compose_down.stderr) or
    ('Removing' in docker_compose_down.stderr)
  loop: "{{ docker_compose_projects_effective }}"
  when: item.state | default('present') == 'absent'
  failed_when: docker_compose_down.rc not in [0, 1]
  become: true

- name: Remove compose directory for disabled projects
  ansible.builtin.file:
    path: "{{ docker_compose_base_dir }}/{{ item.name }}"
    state: absent
  loop: "{{ docker_compose_projects_effective }}"
  when: item.state | default('present') == 'absent'
  become: true
