---
- name: Install Docker repository prerequisites
  ansible.builtin.apt:
    name: "{{ docker_apt_dependencies }}"
    state: present
    update_cache: yes
  become: true

- name: Ensure Docker apt keyring directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Fetch Docker apt GPG key
  ansible.builtin.get_url:
    url: "{{ docker_apt_key_url }}"
    dest: "{{ docker_apt_keyring_path }}"
    mode: '0644'
  become: true

- name: Determine Docker apt architecture
  ansible.builtin.set_fact:
    docker_apt_architecture: "{{ docker_apt_arch_map[ansible_architecture] | default(ansible_architecture) }}"

- name: Configure Docker apt repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ docker_apt_architecture }} signed-by={{ docker_apt_keyring_path }}]
      https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    filename: docker
    state: present
  become: true

- name: Install Docker packages
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes
  become: true

- name: Ensure Docker service is enabled and running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  become: true

- name: Add configured users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users | default([]) }}"
  when: docker_users | default([]) | length > 0
  become: true

- name: Ensure compose base directory exists
  ansible.builtin.file:
    path: "{{ docker_compose_base_dir }}"
    state: directory
    mode: '0755'
  become: true

- name: Aggregate compose projects for host
  ansible.builtin.set_fact:
    docker_compose_projects_effective: "{{ (docker_compose_projects | default([])) + (docker_compose_projects_host | default([])) }}"

- name: Ensure compose project directories exist
  ansible.builtin.file:
    path: "{{ docker_compose_base_dir }}/{{ item.name }}"
    state: directory
    mode: '0755'
  loop: "{{ docker_compose_projects_effective }}"
  when: item.state | default('present') == 'present'
  become: true

- name: Render docker-compose.yml for each project
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_base_dir }}/{{ item.name }}/docker-compose.yml"
    mode: '0644'
  loop: "{{ docker_compose_projects_effective }}"
  when: item.state | default('present') == 'present'
  become: true

- name: Bring compose projects online
  ansible.builtin.command:
    cmd: "docker compose up {{ docker_compose_up_flags }}"
    chdir: "{{ docker_compose_base_dir }}/{{ item.name }}"
  register: docker_compose_up
  changed_when: >-
    ('Creating' in docker_compose_up.stdout) or
    ('Recreating' in docker_compose_up.stdout) or
    ('Pulling' in docker_compose_up.stdout) or
    ('Creating' in docker_compose_up.stderr) or
    ('Recreating' in docker_compose_up.stderr)
  loop: "{{ docker_compose_projects_effective }}"
  when:
    - docker_manage_compose | bool
    - item.state | default('present') == 'present'
  become: true

- name: Tear down disabled compose projects
  ansible.builtin.command:
    cmd: "docker compose down --remove-orphans"
    chdir: "{{ docker_compose_base_dir }}/{{ item.name }}"
  register: docker_compose_down
  changed_when: >-
    ('Stopping' in docker_compose_down.stdout) or
    ('Removing' in docker_compose_down.stdout) or
    ('Stopping' in docker_compose_down.stderr) or
    ('Removing' in docker_compose_down.stderr)
  loop: "{{ docker_compose_projects_effective }}"
  when: item.state | default('present') == 'absent'
  failed_when: docker_compose_down.rc not in [0, 1]
  become: true

- name: Remove compose directory for disabled projects
  ansible.builtin.file:
    path: "{{ docker_compose_base_dir }}/{{ item.name }}"
    state: absent
  loop: "{{ docker_compose_projects_effective }}"
  when: item.state | default('present') == 'absent'
  become: true
