---
- name: Install Docker repository prerequisites
  ansible.builtin.apt:
    name: "{{ docker_apt_dependencies }}"
    state: present
    update_cache: yes
  become: true

- name: Ensure Docker apt keyring directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Fetch Docker apt GPG key
  ansible.builtin.get_url:
    url: "{{ docker_apt_key_url }}"
    dest: "{{ docker_apt_keyring_path }}"
    mode: '0644'
  become: true

- name: Determine Docker apt architecture
  ansible.builtin.set_fact:
    docker_apt_architecture: "{{ docker_apt_arch_map[ansible_architecture] | default(ansible_architecture) }}"

- name: Configure Docker apt repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ docker_apt_architecture }} signed-by={{ docker_apt_keyring_path }}]
      https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    filename: docker
    state: present
  become: true

- name: Install Docker packages
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes
  become: true

- name: Ensure Docker service is enabled and running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  become: true

- name: Add configured users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users | default([]) }}"
  when: docker_users | default([]) | length > 0
  become: true
