# --- MergerFS variables ---
mergefs_branches:
  - mount: "/mnt/parity-hdd"
    device: "/dev/disk/by-label/parity-hdd"
    fstype: "ext4"
    options: "defaults,nofail,noatime"
  - mount: "/mnt/data1-hdd"
    device: "/dev/disk/by-label/data1-hdd"
    fstype: "ext4"
    options: "defaults,nofail,noatime"
  - mount: "/mnt/data2-ssd"
    device: "/dev/disk/by-label/data2-ssd"
    fstype: "ext4"
    options: "defaults,nofail,noatime"
  - mount: "/mnt/data3-ssd"
    device: "/dev/disk/by-label/data3-ssd"
    fstype: "ext4"
    options: "defaults,nofail,noatime"

mergefs_pool_mount: "/mnt/storage"
mergefs_options: >-
  defaults,allow_other,use_ino,cache.files=partial,dropcacheonclose=true,
  category.create=epmfs,minfreespace=50G

# --- SnapRAID variables ---
snapraid_version: "11.5"                   # version installed on pi-nas
snapraid_conf_dir: "/etc/snapraid"
snapraid_arrays:
  - name: "nas"                            # identifier for this array
    conf_dir: "{{ snapraid_conf_dir }}"
    parity_drives:
      - mount: "/mnt/parity-hdd"
    data_drives:
      - { mount: "/mnt/data1-hdd", name: "data1-hdd" }
      - { mount: "/mnt/data2-ssd", name: "data2-ssd" }
      - { mount: "/mnt/data3-ssd", name: "data3-ssd" }
    snapraid_sync:
      - sync_schedule: "0 3 * * *"        # run sync at 03:00 daily
        scrub_schedule: "30 3 * * 0"      # run scrub at 03:30 every Sunday
        delete_threshold: 100             # max deleted files before manual action
        update_threshold: -1              # disable update threshold
        scrub_percent: 8                  # percentage of files to scrub
        scrub_age: 10                     # scrub files older than 10 days

# --- Docker compose projects specific to pi-nas ---
docker_compose_projects_host:
  - name: home-assistant
    compose:
      services:
        home-assistant:
          image: ghcr.io/home-assistant/home-assistant:stable
          container_name: home-assistant
          network_mode: host
          privileged: true
          environment:
            PUID: "1000"
            PGID: "1000"
            TZ: "{{ timezone }}"
          volumes:
            - "{{ mergefs_pool_mount }}/docker-volumes/home-assistant/config:/config"
            - /etc/localtime:/etc/localtime:ro
            - /run/dbus:/run/dbus:ro
          restart: unless-stopped
  - name: plex
    compose:
      services:
        plex:
          image: plexinc/pms-docker:latest
          container_name: plex
          network_mode: host
          environment:
            PLEX_UID: 1000
            PLEX_GID: 1000
            TZ: "{{ timezone }}"
            PLEX_CLAIM: "{{ vault_plex_claim | default('') }}"
          volumes:
            - "{{ mergefs_pool_mount }}/docker-volumes/plex/config:/config"
            - "{{ mergefs_pool_mount }}/docker-volumes/plex/transcode:/transcode"
            - "{{ mergefs_pool_mount }}:/data"
          devices:
            - /dev/dri:/dev/dri
          restart: unless-stopped
  - name: pihole
    compose:
      services:
        pihole:
          image: pihole/pihole:latest
          container_name: pihole
          ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "80:80/tcp"
            - "443:443/tcp"
          environment:
            TZ: "{{ timezone }}"
            FTLCONF_webserver_api_password: "{{ vault_pihole_password | default('changeme') }}"
            FTLCONF_dns_listeningMode: "all"
          cap_add:
            - NET_ADMIN
            - SYS_TIME
            - SYS_NICE
          restart: unless-stopped
          labels:
            - "com.centurylinklabs.watchtower.monitor-only=true"
          volumes:
            - "{{ mergefs_pool_mount }}/docker-volumes/pihole/etc-pihole:/etc/pihole"
