- hosts: all
  become: yes
  roles:
    - role: common
      tags: ['common']
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade packages
      apt:
        upgrade: "{{ apt_upgrade_type | default('full') }}"
